package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    dependencies {
        expect(RelativeId("Build")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "cache.json=>cache"
            }
        }
        update(RelativeId("Build")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = """
                    cache.json=>cache
                    releases/92a4ad08c9040b2a9b12cc9f3d2adf82a0ab8c7ec7e3215db9b4b5d47c110e75.txt=>releases
                """.trimIndent()
            }
        }

    }
}
