package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Checkout"
            id = "Checkout"
            scriptContent = """
                git fetch --all
                git checkout %git.commit.hash%
            """.trimIndent()
        }
        maven {
            name = "Javadoc"
            id = "Javadoc"
            goals = "dokka:javadoc"
        }
        script {
            name = "DownloadReleaseNotes"
            id = "DownloadReleaseNotes"
            scriptContent = """
                INSTALL_DIR="${'$'}HOME/bin"
                mkdir -p "${'$'}INSTALL_DIR"
                
                
                JQ_URL="https://github.com/stedolan/jq/releases/download/jq-1.8.1/jq-linux64"
                curl -L -o "${'$'}INSTALL_DIR/jq" "${'$'}JQ_URL"
                
                chmod +x "${'$'}INSTALL_DIR/jq"
                
                export PATH="${'$'}INSTALL_DIR:${'$'}PATH"
                
                jq --version
                
                mkdir -p cache releases
                
                
                if [ ! -f %env.CACHE_MAP% ]; then
                  echo "Cache not found"
                  echo "{}" > %env.CACHE_MAP%
                fi
                
                CACHED_REFERENCE=${'$'}(jq -r --arg commit %git.commit.hash% '.[${'$'}commit] // empty' %env.CACHE_MAP%)
                echo "Cached reference: ${'$'}CACHED_REFERENCE"
                
                if [ "${'$'}CACHED_REFERENCE" != "" ]; then
                  # First case, artifact was first generated when the marketing website was not reachable
                  # No release notes are added to artifact to ensure reproducibility
                  if [ "${'$'}CACHED_REFERENCE" == "null" ]; then
                    echo "Commit %git.commit.hash% cached without release notes."
                    exit 0
                  # Second case, artifact was already created and we have cached release notes for it
                  else
                    echo "Commit %git.commit.hash% found in cache, checksum: ${'$'}CACHED_REFERENCE"
                    exit 0
                  fi
                fi
                
                # Third case, first time of commit so no cache present, website available
                if curl -sf %env.RELEASE_NOTES_URL% -o tmp_release_notes.txt; then
                  CHECKSUM=${'$'}(sha256sum tmp_release_notes.txt | awk '{print ${'$'}1}')
                  echo "Downloaded release notes, checksum: ${'$'}CHECKSUM"
                  jq --arg commit %git.commit.hash% --arg checksum "${'$'}CHECKSUM" '. + {(${'$'}commit): ${'$'}checksum}' %env.CACHE_MAP% > "%env.CACHE_MAP%.tmp" && mv "%env.CACHE_MAP%.tmp" %env.CACHE_MAP%
                  cp tmp_release_notes.txt "releases/${'$'}CHECKSUM.txt"
                # Fourth case, first time commit, website not available
                else
                  echo "Website unavailable, storing null in cache"
                  jq --arg commit %git.commit.hash% '. + {(${'$'}commit): null}' %env.CACHE_MAP% > "%env.CACHE_MAP%.tmp" && mv "%env.CACHE_MAP%.tmp" %env.CACHE_MAP%
                fi
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(2) {
            clearConditions()
            scriptContent = """
                INSTALL_DIR="${'$'}HOME/bin"
                mkdir -p "${'$'}INSTALL_DIR"
                
                
                JQ_URL="https://github.com/stedolan/jq/releases/download/jq-1.8.1/jq-linux64"
                curl -L -o "${'$'}INSTALL_DIR/jq" "${'$'}JQ_URL"
                
                chmod +x "${'$'}INSTALL_DIR/jq"
                
                export PATH="${'$'}INSTALL_DIR:${'$'}PATH"
                
                jq --version
                
                mkdir -p cache releases release-artifact
                
                
                if [ ! -f %env.CACHE_MAP% ]; then
                  echo "Cache not found"
                  echo "{}" > %env.CACHE_MAP%
                fi
                
                CACHED_REFERENCE=${'$'}(jq -r --arg commit "%git.commit.hash%" '.[${'$'}commit] // empty' "%env.CACHE_MAP%")
                echo "Cached reference: ${'$'}CACHED_REFERENCE"
                
                if [ "${'$'}CACHED_REFERENCE" != "" ]; then
                  # First case, artifact was first generated when the marketing website was not reachable
                  # No release notes are added to artifact to ensure reproducibility
                  if [ "${'$'}CACHED_REFERENCE" == "null" ]; then
                    echo "Commit %git.commit.hash% found without release notes." 
                    exit 0
                  # Second case, artifact was already created and we have cached release notes for it
                  else
                    echo "Commit %git.commit.hash% found in cache, checksum: ${'$'}CACHED_REFERENCE"
                    cp releases/${'$'}CACHED_REFERENCE.txt release-artifact/
                    
                    exit 0
                  fi
                fi
                
                # Third case, first time of commit so no cache present, website available
                if curl -sf %env.RELEASE_NOTES_URL% -o tmp_release_notes.txt; then
                  CHECKSUM=${'$'}(sha256sum tmp_release_notes.txt | awk '{print ${'$'}1}')
                  echo "Downloaded release notes, checksum: ${'$'}CHECKSUM"
                  jq --arg commit %git.commit.hash% --arg checksum "${'$'}CHECKSUM" \
                  '. + {(${'$'}commit): ${'$'}checksum}' %env.CACHE_MAP% > "%env.CACHE_MAP%.tmp" && mv "%env.CACHE_MAP%.tmp" %env.CACHE_MAP%
                  cp tmp_release_notes.txt "releases/${'$'}CHECKSUM.txt"
                  cp releases/${'$'}CHECKSUM.txt release-artifact/
                  
                # Fourth case, first time commit, website not available
                else
                  echo "Website unavailable, storing null in cache"
                  jq --arg commit %git.commit.hash% '. + {(${'$'}commit): null}' \ 
                  %env.CACHE_MAP% > "%env.CACHE_MAP%.tmp" && mv "%env.CACHE_MAP%.tmp" %env.CACHE_MAP%
                fi
                
                
                # Move Javadoc to release artifact
                
                cp -r target/dokkaJavadoc/* release-artifact/
                
                apk add tar
                
                tar --sort=name --mtime='1970-01-01' --owner=0 --group=0 --numeric-owner \
                    -czf release-artifact.tar.gz -C release-artifact .
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }

    dependencies {
        expect(RelativeId("Build")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "cache.json=>cache"
            }
        }
        update(RelativeId("Build")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = """
                    cache.json=>cache
                    *.txt=>releases
                """.trimIndent()
            }
        }

    }
}
